#!/usr/bin/env bash
# Run this ONCE — creates a clickable launcher on your Desktop:
#   ~/Desktop/Bandaru Trade Analysis.command
# After that, double-click that Desktop icon any time to start the dashboard.
# Also removes any previous launcher with the old name.

set -e
cd "$(dirname "$0")"
PROJECT_DIR="$(pwd -P)"

LAUNCHER="$HOME/Desktop/Bandaru Trade Analysis.command"
OLD_LAUNCHER="$HOME/Desktop/SPY 0DTE Analyzer.command"

# Remove old name if it exists
if [ -f "$OLD_LAUNCHER" ]; then
    rm -f "$OLD_LAUNCHER"
    echo "Removed old launcher: $OLD_LAUNCHER"
fi

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Bandaru Trade Analysis Platform — Desktop launcher
# Generated by make-desktop-shortcut.command on $(date "+%Y-%m-%d")
# Thin wrapper that runs the live dashboard in Yahoo Finance mode.
# To regenerate (e.g. after moving the project): re-run make-desktop-shortcut.command.

exec "$PROJECT_DIR/run-live.command"
EOF

chmod +x "$LAUNCHER"

echo ""
echo "================================================"
echo "  Bandaru Trade Analysis — Desktop launcher ready"
echo "================================================"
echo ""
echo "Look on your Desktop for:"
echo "    Bandaru Trade Analysis.command"
echo ""
echo "Double-click it any time to start the dashboard."
echo ""
echo "Tip — give it a friendlier appearance:"
echo "  • Right-click the launcher → Get Info"
echo "  • Drag any image (.icns or .png) onto the small icon at the top of the Info window"
echo "  • Optionally rename it (e.g. 'Bandaru Dashboard')"
echo ""
echo "To uninstall: just drag the Desktop file to Trash."
echo ""
read -p "Press Enter to close this window…"
